name: Release

#on:
#  push:
#    tags:
#      - "v[0-9]+.[0-9]+.[0-9]+"
      
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # JJGR: Change back to main from cicd
  # tag:
  # Allows you to run this workflow manually from the Actions tab
  # schedule:
  #  - cron: "0 0 1 * *" # monthly
  workflow_dispatch:
  
jobs:
  build:
    name: Release
    runs-on: ubuntu-20.04

    steps:
      - name: Get version
        id: get_version
        run: |
          export VERSION="${GITHUB_REF/refs\/tags\//}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Prepare environment
        run: |
          sudo apt install build-essential automake autoconf git squashfs-tools ssh-askpass pkg-config curl wget
          wget 'https://github.com/fwup-home/fwup/releases/download/v1.8.4/fwup_1.8.4_amd64.deb'
          sudo dpkg -i ./*.deb

      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '23.3'
          elixir-version: '1.12.0'

      - name: Prepare Nerves
        run: |
          mkdir ~/.ssh
          cp ./id_ed25519* ~/.ssh/
          chmod 700 ~/.ssh
          chmod 644 ~/.ssh/id_ed25519.pub
          chmod 600 ~/.ssh/id_ed25519

          mix local.hex --force
          mix local.rebar --force
          mix archive.install --force hex nerves_bootstrap

      - name: Install dependencies
        run: make dependencies

      - name: Build release
        run: make release

      - name: Pack release
        run: tar -czf ./kiwi.tar.gz kiwi.fw
        
      # Upload everything
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: kiwi
          path: ./kiwi.tar.gz

      # Create release
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v0.${{ steps.clone_repo.outputs.VERSION }}
          name: kiwi_0.${{ steps.clone_repo.outputs.VERSION }}
          draft: false
          prerelease: false
          artifactErrorsFailBuild: true
          artifacts: "kiwi.zip"
          artifactContentType: application/zip
          token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Generate changelog
#        run: |
#          git log $(git tag --sort=-version:refname | head -n 2 | tail -n 1)...${{ github.ref }} --pretty=format:'<li> <a href="http://github.com/mrusme/kiwi/commit/%H">view commit &bull;</a> %s</li> ' --reverse > ${{ github.workflow }}-CHANGELOG.txt
          
#      - name: Release
#        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          body_path: ${{ github.workflow }}-CHANGELOG.txt
#          files: |
#            kiwi.tar.gz
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
